### ISSUE TITLE
StringProperty can only accepts strings

### ISSUE THREAD

**Issue by artenverho** [Schlaubischlump/shairport-metadatareader-python#1]
Hi Schlaubischlump,

I have tried to install and run one of the example scripts and I seem to get the following error:

```
  File "simple_print.py", line 11, in <module>
    from shairportmetadatareader.util import IS_PY2
  File "/usr/local/lib/python2.7/dist-packages/shairportmetadatareader/__init__.py", line 2, in <module>
    from .airplaylistener import AirplayListener, DEFAULT_PIPE_FILE, DEFAULT_SOCKET
  File "/usr/local/lib/python2.7/dist-packages/shairportmetadatareader/airplaylistener.py", line 61, in <module>
    class AirplayListener(EventDispatcher):
  File "/usr/local/lib/python2.7/dist-packages/shairportmetadatareader/airplaylistener.py", line 78, in AirplayListener
    client_name = StringProperty([])
  File "/usr/local/lib/python2.7/dist-packages/eventdispatcher/stringproperty.py", line 24, in __init__
    raise ValueError('StringProperty can only accepts strings.')
ValueError: StringProperty can only accepts strings.
```

Probably I am doing something wrong here. Can you help?

Thanks! I am curious if I can use your tool!

Arten

**Comment by artenverho** [comment]
I found a temporary fix

I changed the Evendispatcher part in the the airplay listener.py from:
 ```
   client_name = StringProperty([])
    '''Name of the airplay client e.g John's iPhone.'''

    playback_state = StringProperty("stop", options=["play", "pause", "stop"])
    '''Playback state.'''
```

to

```
    client_name = StringProperty("")
    '''Name of the airplay client e.g John's iPhone.'''

   #playback_state = StringProperty("stop", options=["play", "pause", "stop"])
    '''Playback state.'''
```

I am probably missing some info now but at least I can run the code..

my plan is to use the code to make a simple arduino based USB display/remote that shows the currently played song and can control the client with hardware buttons.

cheers,

Arten

**Comment by Schlaubischlump** [comment]
Hi Arten, 

I only tested the code with kivy, not with eventdispatcher. Of course playback_state should be an OptionProperty, not a StringProperty. I pushed an updated version, which should fix this error. Could you please test the new version and report back ? Which version of python did you use ? 

If you need further help on how to use the library let me know.

Schlaubi
