### ISSUE TITLE
ssnc aend unknown

### ISSUE THREAD

**Issue by yjeanrenaud** [Schlaubischlump/shairport-metadatareader-python#5]
When the AirPlay-client disconnects, it seesm shairport-sync sends out a metadata unknown to the python reader:
`Unknown shairport-sync core (ssnc) code "aend", with base64 data None.`

**Comment by Schlaubischlump** [comment]
I'm not sure, what this code is used for, but you should be able to safely ignore the message.

**Comment by Schlaubischlump** [comment]
The codes "abeg" and "aend" are used by shairport sync for airplay 2.

**Comment by austinliuu** [comment]
Is there a way to capture these code? I would need to track the play/paused status and I noticed it is reflected by paus/disc/pres code

**Comment by Schlaubischlump** [comment]
Yes, you can listen to the "on_item" callback and handle the code manually.

**Comment by austinliuu** [comment]
I tried with `listener.bind(on_item= print_play_status)` but still can't see the printout of status but the WARNING message like
` [WARNING] Unknown shairport-sync core (ssnc) code "paus", with base64 data None.`
Am I doing it correctly?

**Comment by austinliuu** [comment]
Or should I update the  `CORE_CODE_WHITELIST `list variable?

**Comment by austinliuu** [comment]
Okay I tried `listener.bind(playback_state= print_play_status)` and it seems to work with a small delay, I guess it is because the event code is still based from Airplay 1
